# Generated by Django 3.2.7 on 2021-10-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_auto_20211017_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='from_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.post'),
        ),
    ]
