# Generated by Django 3.2.7 on 2021-10-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_comment_from_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='from_post',
        ),
    ]
